server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testTopic
    username: roll
    password: tide
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: hydra-discovery-service.cfapps.io