server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testUser
    username: roll
    password: tide
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/